---
# -------------------------------------------------------------------------#
# Rubyに必要なパッケージ一覧をインストール
# -------------------------------------------------------------------------#
- name: Required Packages for Ruby
  yum:
    name:
      - gcc-c++
      - make
      - patch
      - curl
      - zlib-devel
      - openssl-devel
      - ImageMagick-devel
      - readline-devel
      - libcurl-devel
      - libffi-devel
      - libicu-devel
      - libxml2-devel
      - libxslt-devel
      - mysql-devel
    state: latest

# -------------------------------------------------------------------------#
# yarn Repo Registar and Install
# -------------------------------------------------------------------------#
- name: Registration yarn on Yum repo
  shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo

- name: yarn Install
  yum:
    name: yarn
    state: latest

- name: Install Ruby
  yum:
    name: https://github.com/feedforce/ruby-rpm/releases/download/2.6.3/ruby-2.6.3-1.el7.centos.x86_64.rpm
    state: present
